version: '3.7'

services:
  app:
    build: .
    image: 'receipt-app'
    container_name: 'receipt-app'
    ports:
      - "8080:8080"
    depends_on:
      - database

  database:
    image: 'postgres:16.2'
    container_name: 'receipt-database'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "letmein"
      POSTGRES_DB: "receipt"